#!/usr/bin/perl -w
use strict;
use lib qw( lib ../lib );
use lib qw( extlib ../extlib );
use lib qw( plugins/TweetFlickrPhotostream/lib ../plugins/TweetFlickrPhotostream/lib );
use lib qw( plugins/TweetFlickrPhotostream/extlib ../plugins/TweetFlickrPhotostream/extlib );

use MT;

my $photo_id = 0;
my $blog_id = 0;

require Getopt::Long;
Getopt::Long::GetOptions(
    "photo_id=i" => \$photo_id,
    "blog_id=i" => \$blog_id,
);

my $app = MT->instance;
if ( my $plugin = $app->component( 'TweetFlickrPhotostream' ) ) {
    if ( $photo_id && $photo_id =~ /^[0-9]{1,}$/ ) {
        require TweetFlickrPhotostream::Util;
        if ( $blog_id && $blog_id =~ /^[0-9]{1,}$/ ) {
            TweetFlickrPhotostream::Util::tweet_flickr_photostream_by_id( $photo_id, $blog_id );
        } else {
            print TweetFlickrPhotostream::Util::shorter_url( $photo_id ) . "\n";
        }
    } else {
        require TweetFlickrPhotostream::Tasks;
        TweetFlickrPhotostream::Tasks::tweet_flickr_photostream();
    }
}

1;
