#!/usr/bin/perl -w

use strict;
use lib 'lib', '../lib';
use lib 'extlib', '../extlib';
use MT;

my $photo_id = 0;
my $blog_id = 0;

require Getopt::Long;
Getopt::Long::GetOptions(
    "photo_id=i" => \$photo_id,
    "blog_id=i" => \$blog_id,
);

my $app = MT->instance;
if ( my $plugin = $app->component( 'TweetFlickrPhotostream' ) ) {
    if ( $photo_id && $photo_id =~ /^[0-9]{1,}$/ ) {
        if ( $blog_id && $blog_id =~ /^[0-9]{1,}$/ ) {
            MT::Plugin::TweetFlickrPhotostream::tweet_flickr_photostream_by_id( $photo_id, $blog_id );
        } else {
            print MT::Plugin::TweetFlickrPhotostream::get_shorter_url( $photo_id ) . "\n";
        }
    } else {
        $plugin->tweet_flickr_photostream();
    }
}

1;
